server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:./medium_dev;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
